	<!-- END OF BODY -->
</div>
<hr>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="<!--#echo var="baseURI"-->/js/bootstrap.js"></script>

<center>
	<a href="http://wpi.edu/"><img height="64" width="198" src="<!--#echo var="baseURI"-->img/wpi.png" style="margin: 20px;"></a>
	<a href="http://www.siam.org/"><img height="64" width="171" src="<!--#echo var="baseURI"-->img/siam.png" style="margin: 20px;"></a>
</center>

  </body>
</html>
