<!DOCTYPE html>
<!--#set var="baseURI" value="/~siam/new/"-->
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>SIAM</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link href="<!--#echo var="baseURI"-->css/bootstrap.css" rel="stylesheet">
	<style type="text/css">
	body {
		padding-top: 60px;
	}
	</style>
	<link href="<!--#echo var="baseURI"-->css/bootstrap-responsive.css" rel="stylesheet">

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
      <![endif]-->
  </head>

  <body>
  	<div class="navbar navbar-inverse navbar-fixed-top">
  		<div class="navbar-inner">
  			<div class="container">
  				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</button>
  				<a class="brand" href="#"><img src="<!--#echo var="baseURI"-->/logo.png"></a>
  				<div class="nav-collapse collapse">
  					<!--#include virtual="menu.inc" -->
  					<div class="navbar-form pull-right">
  						JOIN!
  					</div>
  				</div><!--/.nav-collapse -->
  			</div>
  		</div>
  	</div>
  	<div class="container">
    <!-- BEGGINING OF BODY -->