<!--#include virtual="../header.inc"-->

<div class="span3">
  <div class="well sidebar-nav" style=" padding: 9px 0;">
    <ul class="nav nav-list">
      <li class="nav-header">Events</li>
      <li <!--#if expr="$REQUEST_URI = /1213/"--> class="active" <!--#endif -->><a href="../1213">2012-2013</a></li>
      <li <!--#if expr="$REQUEST_URI = /1112/"--> class="active" <!--#endif -->><a href="../1112">2011-2012</a></li>
      <li <!--#if expr="$REQUEST_URI = /1011/"--> class="active" <!--#endif -->><a href="../1011">2010-2011</a></li>
      <li <!--#if expr="$REQUEST_URI = /0910/"--> class="active" <!--#endif -->><a href="../0910">2009-2010</a></li>
      <li <!--#if expr="$REQUEST_URI = /0809/"--> class="active" <!--#endif -->><a href="../0809">2008-2009</a></li>
      <li <!--#if expr="$REQUEST_URI = /0708/"--> class="active" <!--#endif -->><a href="../0708">2007-2008</a></li>
      <li <!--#if expr="$REQUEST_URI = /0607/"--> class="active" <!--#endif -->><a href="../0607">2006-2007</a></li>
      <li <!--#if expr="$REQUEST_URI = /0506/"--> class="active" <!--#endif -->><a href="../0506">2005-2006</a></li>
      <li <!--#if expr="$REQUEST_URI = /0405/"--> class="active" <!--#endif -->><a href="../0405">2004-2005</a></li>
      <li <!--#if expr="$REQUEST_URI = /0304/"--> class="active" <!--#endif -->><a href="../0304">2003-2004</a></li>
    </ul>
  </div>
</div>
<div class="span8"> 